// Code generated by Lark OpenAPI.

package bitable

import (
	"github.com/lincaiyong/larkbase/larksuite/core"
)

type Service struct {
	*V1
}

func NewService(config *larkcore.Config) *Service {
	return &Service{
		V1: New(config),
	}
}
